# Generated by Django 4.1.2 on 2022-10-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_student_firstname_alter_student_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
