# Generated by Django 4.1.2 on 2022-10-16 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_student_is_active_student_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('blog_info', models.CharField(max_length=400)),
                ('blog_upload_date', models.DateTimeField(auto_now_add=True)),
                ('blog_writer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
