# Generated by Django 4.1.2 on 2022-10-16 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_notes_blog_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='blog_writer',
        ),
        migrations.AddField(
            model_name='notes',
            name='blog_writer',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
